In [1]:
import pandas as pd
import numpy as np

from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

In [4]:
!pip install geopy

Collecting geopy
  Downloading geopy-2.4.1-py3-none-any.whl.metadata (6.8 kB)
Collecting geographiclib<3,>=1.52 (from geopy)
  Downloading geographiclib-2.1-py3-none-any.whl.metadata (1.6 kB)
Downloading geopy-2.4.1-py3-none-any.whl (125 kB)
Downloading geographiclib-2.1-py3-none-any.whl (40 kB)
Installing collected packages: geographiclib, geopy
Successfully installed geographiclib-2.1 geopy-2.4.1

In [2]:
# 1 m2 to ft2
m2_to_ft2 = 10.764

# url for different datasets
sales_consideration_url = "http://www.rvd.gov.hk/datagovhk/7.3.csv"
secondary_avg_price_district_url = "http://www.rvd.gov.hk/datagovhk/1.2M.csv"
vacancy_rate_url = "http://www.rvd.gov.hk/datagovhk/Private_Domestic-Vacancy.csv"

### Primary and secondary sales amount and consideration by year

In [3]:
sales_considerations_df = pd.read_csv(sales_consideration_url, skiprows = 1, encoding = "utf-8")

In [4]:
# done
sales_considerations_df.head()

,Month,Primary Sales Number,Primary Sales Consideration,Secondary Sales Number,Secondary Sales Consideration
0,01-2002,2718,8218,5129,9966
1,02-2002,1506,4305,4189,8070
2,03-2002,1709,4190,3741,6795
3,04-2002,2543,6516,4866,8739
4,05-2002,2257,5844,5068,11097

In [5]:
sales_considerations_df.to_csv("sales_numbers_with_considerations.csv", index = False, encoding = "utf-8")

### Secondary consideration by district

In [6]:
secondary_avg_price_district_df = pd.read_csv(secondary_avg_price_district_url, skiprows = 1, encoding = "utf-8")

In [7]:
secondary_avg_price_district_df.head()

,Month,Class A Hong Kong,Class A Hong Kong - Remarks,Class A Kowloon,Class A Kowloon - Remarks,Class A New Territories,Class A New Territories - Remarks,Class B Hong Kong,Class B Hong Kong - Remarks,Class B Kowloon,...,Class D Kowloon,Class D Kowloon - Remarks,Class D New Territories,Class D New Territories - Remarks,Class E Hong Kong,Class E Hong Kong - Remarks,Class E Kowloon,Class E Kowloon - Remarks,Class E New Territories,Class E New Territories - Remarks
0,01-1999,42663,NaN,36842,NaN,36679,NaN,50141,NaN,37945,...,56292,NaN,50457,NaN,72978,NaN,62551,Z,50968,NaN
1,02-1999,43068,NaN,35834,NaN,36802,NaN,47950,NaN,38428,...,54817,NaN,46759,NaN,66326,NaN,59774,Z,45945,NaN
2,03-1999,42683,NaN,36731,NaN,36992,NaN,51060,NaN,38254,...,51646,NaN,50737,NaN,74608,NaN,61790,Z,46120,NaN
3,04-1999,43223,NaN,36543,NaN,36485,NaN,50189,NaN,39445,...,48628,NaN,43915,NaN,73489,NaN,75745,Z,46953,Z
4,05-1999,43316,NaN,36449,NaN,38035,NaN,50650,NaN,37945,...,50312,NaN,48495,NaN,78077,NaN,86018,Z,50454,NaN

In [8]:
# include only columns with consideration without remarks columns
col_list = []

for col in secondary_avg_price_district_df.columns:
    if 'remarks' not in col.lower():
        col_list.append(col)

In [9]:
result_df = secondary_avg_price_district_df[col_list]

In [10]:
result_df.tail()

,Month,Class A Hong Kong,Class A Kowloon,Class A New Territories,Class B Hong Kong,Class B Kowloon,Class B New Territories,Class C Hong Kong,Class C Kowloon,Class C New Territories,Class D Hong Kong,Class D Kowloon,Class D New Territories,Class E Hong Kong,Class E Kowloon,Class E New Territories
322,11-2025,135832,116077,112115,141364,130928,109271,166371,172853,114704,198897,177561,113815,219399,202640,100413
323,12-2025,136878,118338,115164,139422,131141,107333,163705,174967,119169,198286,169259,107733,259655,162908,100185
324,01-2026,138129,122677,116994,143784,129117,110327,165730,160179,125184,183962,191449,114924,261699,174749,84710
325,02-2026,141467,127581,121357,145780,133838,113632,174921,165444,121534,199233,187902,113085,323894,211048,97216
326,03-2026,140442,128140,123740,148636,136937,113073,176485,170773,123491,199489,192586,123753,235913,214558,103942

In [11]:
# unpivot the dataframe to have a long format
result_melt_df = pd.melt(result_df, id_vars = ['Month'], var_name = 'property_category', value_name = 'secondary_consideration')

In [12]:
class_filter = ['Class A', 'Class B']
df_test = result_melt_df.head(0)

for class_str in class_filter:
    df_temp = result_melt_df[result_melt_df['property_category'].str.contains(class_str)]
    df_test = pd.concat([df_test, df_temp])

In [13]:
df_test.head()

     Month  property_category secondary_consideration
0  01-1999  Class A Hong Kong                   42663
1  02-1999  Class A Hong Kong                   43068
2  03-1999  Class A Hong Kong                   42683
3  04-1999  Class A Hong Kong                   43223
4  05-1999  Class A Hong Kong                   43316

In [14]:
result_melt_df.tail()

        Month        property_category secondary_consideration
4900  11-2025  Class E New Territories                  100413
4901  12-2025  Class E New Territories                  100185
4902  01-2026  Class E New Territories                   84710
4903  02-2026  Class E New Territories                   97216
4904  03-2026  Class E New Territories                  103942

In [15]:
# separate property category into class and district columns, and remove prefix and suffix spaces
result_melt_df['district'] = result_melt_df['property_category'].str[7:].str.strip()
result_melt_df['property_category'] = result_melt_df['property_category'].str[:7].str.strip()

In [16]:
# convert the secondary consideration to numeric and replace '-' with 0
result_melt_df['secondary_consideration'] = result_melt_df['secondary_consideration'].replace('-', 0)

# convert the consideration from per m2 to per ft2
result_melt_df['secondary_consideration'] = result_melt_df['secondary_consideration'].astype('float') / m2_to_ft2

In [17]:
# rearrange the columns
secondary_avg_price_district_output_df = result_melt_df[['Month','district','property_category','secondary_consideration']]

In [18]:
secondary_avg_price_district_output_df.to_csv('secondary_avg_price_district.csv', index = False, encoding = 'utf-8-sig')

### Vacancy rate

In [19]:
vacancy_df = pd.read_csv(vacancy_rate_url, skiprows = 1, encoding = "utf-8")

In [20]:
vacancy_df.head()

,Year,Class A (Vacancy) - Unit,Class A (Vacancy) - %,Class B (Vacancy) - Unit,Class B (Vacancy) - %,Class C (Vacancy) - Unit,Class C (Vacancy) - %,Class D (Vacancy) - Unit,Class D (Vacancy) - %,Class E (Vacancy) - Unit,Class E (Vacancy) - %,Total (Vacancy) - Unit,Total (Vacancy) - %
0,1985,9085,0.037,7845,0.032,2420,0.044,1930,0.062,810,0.049,22090,0.037
1,1986,10175,0.039,9170,0.036,2035,0.035,2100,0.065,1185,0.068,24665,0.039
2,1987,7220,0.026,10560,0.039,2255,0.037,1515,0.045,780,0.044,22330,0.034
3,1988,5870,0.021,7845,0.027,3055,0.048,2200,0.061,1255,0.067,20225,0.029
4,1989,6135,0.021,17620,0.057,3450,0.051,1840,0.049,1250,0.064,30295,0.042

In [21]:
# create column name lists for unit and percent columns
unit_col_list = list()
percent_col_list = list()

for col in vacancy_df.columns:
    if 'year' in col.lower():
        unit_col_list.append(col)
        percent_col_list.append(col)
    elif 'unit' in col.lower():
        unit_col_list.append(col)
    elif '%' in col.lower():
        percent_col_list.append(col)

In [22]:
# create two separate dataframes for unit and percent columns
vacancy_unit_df = vacancy_df[unit_col_list]
vacancy_percent_df = vacancy_df[percent_col_list]

In [23]:
# unpivot to the table as long format
vacancy_unit_melt_df = pd.melt(vacancy_unit_df, id_vars=['Year'], var_name='vacancy_class', value_name='vacancy_unit')
vacancy_percent_df = pd.melt(vacancy_percent_df, id_vars=['Year'], var_name='vacancy_class', value_name='vacancy_percent')

# remove the extra string in the vacancy_class column in readable format 
vacancy_unit_melt_df['vacancy_class'] = vacancy_unit_melt_df['vacancy_class'].str.replace('(Vacancy) - Unit', '').str.strip()
vacancy_percent_df['vacancy_class'] = vacancy_percent_df['vacancy_class'].str.replace('(Vacancy) - %', '').str.strip()

# join the two dataframes together
vacancy_overall_df = pd.merge(vacancy_unit_melt_df, vacancy_percent_df, on=['Year', 'vacancy_class'])

In [24]:
vacancy_overall_df.head()

   Year vacancy_class  vacancy_unit  vacancy_percent
0  1985       Class A          9085            0.037
1  1986       Class A         10175            0.039
2  1987       Class A          7220            0.026
3  1988       Class A          5870            0.021
4  1989       Class A          6135            0.021

In [25]:
# export as csv file
vacancy_overall_df.to_csv('annual_vacancy_rate.csv', index=False, encoding='utf-8-sig')

### HOS 2nd market

In [6]:
hos_df = pd.read_csv('HOS_transaction_records_2020_2025.csv', encoding='utf-8')

In [7]:
hos_df.head()

,Location,Court_Estate_Name,Transaction_Price,Saleable_Floor_Area_sq_ft,Saleable_Floor_Area_sq_m,Transaction_Price_sq_ft,Transaction_Price_sq_m,Floor_Level,Discount_Rate,agency_self_negotiation,District,Year,Month
0,Chai Wan,Cheerful Garden,"5,700,000",592,55,"9,628","103,636",M,47,A,Eastern,2020,1
1,Chai Wan,Hang Tsui Court,"3,750,000",407,38,"9,216","99,206",M,46,S,Eastern,2020,1
2,Chai Wan,Harmony Garden,"4,500,000",431,40,"10,452","112,500",M,45,A,Eastern,2020,1
3,Chai Wan,Kai Tsui Court,"3,880,000",435,40,"8,922","96,040",H,47,A,Eastern,2020,1
4,Chai Wan,Lok Hin Terrace,"5,700,000",580,54,"9,825","105,751",M,48,A,Eastern,2020,1

In [8]:
hos_df['Address'] = hos_df['Court_Estate_Name'] + ', ' + hos_df['Location'] + ', Hong Kong'

In [24]:
geolocator = Nominatim(user_agent="hk_dashboard")
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)

In [ ]:
## function to get the latitude and longitude of a location
def get_coordinates(location_name):

    try:
        location = geocode(location_name)
        
        if location:
            print("lat and long retrieved successfully")
            return pd.Series([location.latitude, location.longitude])

        else:
            print("location not found")
            return pd.Series([None, None])
        
    except Exception as e:
        print("error and location not found")
        return pd.Series([None, None])

In [28]:
hos_df[['Latitude','Longitude']] = hos_df['Address'].apply(get_coordinates)

lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
location not found
location not found
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
location not found
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
location not found
location not found
location not found
location not found
location not found
location not found
location not found
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
location not found
location not found
location not found
location not found
location not found
location not found
location not found
lat and long retrieved successfully
lat and long retrieved successfully
location not found
location not found
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
location not found
location not found
location not found
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
location not found
location not found
location not found
location not found
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
location not found
location not found
location not found
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
location not found
location not found
location not found
location not found
location not found
location not found
location not found
location not found
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
location not found
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
location not found
location not found
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
location not found
location not found
location not found
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
location not found
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
location not found
location not found
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
location not found
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
location not found
location not found
location not found
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
location not found
lat and long retrieved successfully
location not found
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
location not found
lat and long retrieved successfully
location not found
location not found
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
location not found
location not found
location not found
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
location not found
location not found
location not found
location not found
location not found
lat and long retrieved successfully
location not found
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
location not found
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully
lat and long retrieved successfully

In [30]:
hos_df.head()

,Location,Court_Estate_Name,Transaction_Price,Saleable_Floor_Area_sq_ft,Saleable_Floor_Area_sq_m,Transaction_Price_sq_ft,Transaction_Price_sq_m,Floor_Level,Discount_Rate,agency_self_negotiation,District,Year,Month,Address,Latitude,Longitude
0,Chai Wan,Cheerful Garden,"5,700,000",592,55,"9,628","103,636",M,47,A,Eastern,2020,1,"Cheerful Garden, Chai Wan, Hong Kong",22.263103,114.250563
1,Chai Wan,Hang Tsui Court,"3,750,000",407,38,"9,216","99,206",M,46,S,Eastern,2020,1,"Hang Tsui Court, Chai Wan, Hong Kong",22.267312,114.241447
2,Chai Wan,Harmony Garden,"4,500,000",431,40,"10,452","112,500",M,45,A,Eastern,2020,1,"Harmony Garden, Chai Wan, Hong Kong",22.265422,114.248968
3,Chai Wan,Kai Tsui Court,"3,880,000",435,40,"8,922","96,040",H,47,A,Eastern,2020,1,"Kai Tsui Court, Chai Wan, Hong Kong",22.261599,114.251108
4,Chai Wan,Lok Hin Terrace,"5,700,000",580,54,"9,825","105,751",M,48,A,Eastern,2020,1,"Lok Hin Terrace, Chai Wan, Hong Kong",22.263986,114.240934

In [31]:
hos_df.to_csv('HOS_transaction_records_2020_2025_with_coordinates.csv', index=False, encoding='utf-8-sig')

### Import the manual found latitude location

In [4]:
lat_long_df = pd.read_csv("estate_with_coordinates.csv", encoding='utf-8')
hos_df = pd.read_csv('HOS_transaction_records_2020_2025_with_coordinates.csv', encoding='utf-8')

In [9]:
hos_lat_long_df = hos_df.merge(lat_long_df, left_on='Address', right_on='Address', how='left', suffixes=(None, '_backup'))

In [11]:
hos_df['Latitude'] = hos_lat_long_df['Latitude'].fillna(hos_lat_long_df['Latitude_backup'])
hos_df['Longitude'] = hos_lat_long_df['Longitude'].fillna(hos_lat_long_df['Longitude_backup'])

In [18]:
hos_df.to_csv('HOS_transaction_records_2020_2025_with_full_coordinates.csv', index=False, encoding='utf-8-sig')